RATING_COLUMN_NUMBER = 1
COUNTRY_COLUMN_NUMBER = 2
CLUB_COLUMN_NUMBER = 3

MAX_CLUSTER_NUMBERS = 100
NUMBER_OF_RUNS = 10

MIN_PLAYER_NUMBER = 0
MAX_PLAYER_NUMBER = MAX_CLUSTER_NUMBERS - 1

MIN_RATING = 71
MAX_RATING = 94
RATING_RANGE = MAX_RATING - MIN_RATING

CLUSTER_NUMBERS = 5

FILE_NAME = "../docs/fifa_players.csv"
